name: Build Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch: # This line adds manual trigger support

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone arm-eabi-4.6 repository
        run: git clone https://github.com/opensource591/arm-eabi-4.6 gcc

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi

      - name: Set up environment
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          export CROSS_COMPILE=${PWD}/gcc/bin/arm-eabi-

          mkdir -p kernel_out

      - name: Configure kernel
        run: |
          cp -f ./arch/arm/configs/cyanogenmod_kylevess_defconfig ./kernel_out/.config
          make -j8 ARCH=arm KBUILD_OUTPUT=./kernel_out oldnoconfig

      - name: Build kernel
        run: |
          make -j8 ARCH=arm KBUILD_OUTPUT=./kernel_out

      - name: Copy kernel image
        run: |
          cp -f ./kernel_out/arch/arm/boot/zImage ./arch/arm/boot/
          cp -f ./kernel_out/arch/arm/boot/compressed/vmlinux ./arch/arm/boot/compressed/
          cp -f ./kernel_out/vmlinux ./
